# 模拟/演练环境 (Simulation / Pre-Prod)
connector:
  node-id: ${spring.cloud.client.ip-address}:${server.port}

services:
  auth:
    id: authorization-service
  subscription:
    id: developer


spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-moni.chanjet.com:8848
        namespace: moni-namespace-uuid

logging:
  level:
    com.chanjet.connector: DEBUG # 模拟环境开启 Debug 日志方便排查
