# 本地开发环境 (Local Development)
connector:
  node-id: 127.0.0.1:8080

services:
  auth:
    id: "" 
  subscription:
    id: ""

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
  cloud:
    nacos:
      discovery:
        server-addr: http://mse-a5fe1032-nacos-ans.mse.aliyuncs.com:8848
        namespace: C6356-inte
        group: OPEN
        enabled: true
        access-key: LTAI5tEwgVWjAmAyGcL2ByQQ # gitleaks:allow
        secret-key: ENC(chanjet||kfpt.inte||vault:v1:lxo0vvTA4SDI2e1O3D3To+A/aTPeKnuFQTaqpuJc7xCcbqte9J/1Vz3uugttdIb8bcf6H3/gTuZWSg==)
