# 集成测试环境 (Integration Test)
connector:
  node-id: ${spring.cloud.client.ip-address}:8080

services:
  auth:
    id: authorization-service
  subscription:
    id: developer

spring:
  data:
    redis:
      cluster:
        nodes: redis-inte-01:6379,redis-inte-02:6379
  cloud:
    nacos:
      discovery:
        server-addr: http://mse-a5fe1032-nacos-ans.mse.aliyuncs.com:8848
        namespace: C6356-inte
        group: OPEN
        enabled: true
        access-key: LTAI5tEwgVWjAmAyGcL2ByQQ # gitleaks:allow
        secret-key: ENC(chanjet||kfpt.inte||vault:v1:lxo0vvTA4SDI2e1O3D3To+A/aTPeKnuFQTaqpuJc7xCcbqte9J/1Vz3uugttdIb8bcf6H3/gTuZWSg==)
